# fly.toml app configuration file generated for leetpulse-backend on 2026-05-03T00:52:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'leetpulse-backend'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  min_machines_running = 0

[[mounts]]
  source = "leetpulse_chroma"
  destination = "/data/chroma"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
